# Generated by Django 5.1.2 on 2024-10-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=50, unique=True, verbose_name='Отдел')),
                ('departmentBoss', models.CharField(default='Генеральный директор', max_length=40, verbose_name='Начальник')),
                ('departmentEmployeesCount', models.IntegerField(verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': ('Отдел',),
                'verbose_name_plural': ('Отделы',),
                'ordering': ['departmentName'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeSurname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('employeeName', models.CharField(max_length=40, verbose_name='Имя')),
                ('employeePatronymic', models.CharField(max_length=40, verbose_name='Отчество')),
                ('employeeJobTitle', models.CharField(max_length=30, verbose_name='Должность')),
                ('employeeBirthDate', models.DateField(verbose_name='Дата рождения')),
                ('employeePhoto', models.ImageField(unique=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': ('Сотрудник',),
                'verbose_name_plural': ('Сотрудники',),
                'ordering': ['employeeSurname'],
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=40, verbose_name='Имя сотрудника')),
                ('employeeSalary', models.IntegerField(verbose_name='Зарплата')),
                ('employeeId', models.OneToOneField(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='eployees_app.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': ('Бухгалтерия',),
                'ordering': ['employeeName'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(blank=True, max_length=40, verbose_name='Ответственный сотрудник')),
                ('task', models.CharField(max_length=50, verbose_name='Задача')),
                ('dateCreation', models.DateField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('customerOrganization', models.CharField(max_length=40, verbose_name='Заказчик')),
                ('taskDescription', models.TextField(null=True, verbose_name='Описание задачи')),
                ('department', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eployees_app.departments', verbose_name='Ответственный отдел')),
                ('employeeId', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eployees_app.employees', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': ('Рабочий план',),
                'ordering': ['task'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=40, verbose_name='Задача')),
                ('customerName', models.CharField(max_length=40, verbose_name='Заказчик')),
                ('taskId', models.ManyToManyField(max_length=40, to='eployees_app.workplan', verbose_name='Задача')),
            ],
            options={
                'verbose_name': ('Заказчик',),
                'verbose_name_plural': ('Заказчики',),
                'ordering': ['task'],
            },
        ),
    ]
