# Generated by Django 5.1.2 on 2024-10-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eployees_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customerName'], 'verbose_name': ('Заказчик',), 'verbose_name_plural': ('Заказчики',)},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='employee',
        ),
        migrations.AlterField(
            model_name='workplan',
            name='employeeId',
            field=models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eployees_app.employees', verbose_name='Ответственный сотрудник'),
        ),
    ]
