# Generated by Django 5.1.2 on 2024-10-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eployees_app', '0002_alter_customer_options_remove_customer_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='department',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='eployees_app.departments', verbose_name='Ответственный отдел'),
        ),
    ]
