# Generated by Django 5.1.2 on 2024-10-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eployees_app', '0003_workplan_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='employeeId',
        ),
        migrations.AlterField(
            model_name='accounting',
            name='employeeName',
            field=models.OneToOneField(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='eployees_app.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='taskDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задачи'),
        ),
    ]
